######################################################################
##
## Filename: ComplexMultiplier_tb.udo
## Created on: Sun Jun 02 10:03:58 PM Iran Standard Time 2024
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
