# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: F:/intel_project/AX7010/11_ad9280_dma_hdmi/ad9280_dma_hdmi.srcs/sources_1/bd/design_1/ip/design_1_ad9280_sample_0_0/design_1_ad9280_sample_0_0.xci
# IP: The module: 'design_1_ad9280_sample_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: f:/intel_project/AX7010/11_ad9280_dma_hdmi/ad9280_dma_hdmi.srcs/sources_1/bd/design_1/ip/design_1_ad9280_sample_0_0/src/afifo/afifo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==afifo || ORIG_REF_NAME==afifo} -quiet] -quiet

# XDC: f:/intel_project/AX7010/11_ad9280_dma_hdmi/ad9280_dma_hdmi.srcs/sources_1/bd/design_1/ip/design_1_ad9280_sample_0_0/src/afifo/afifo.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==afifo || ORIG_REF_NAME==afifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/intel_project/AX7010/11_ad9280_dma_hdmi/ad9280_dma_hdmi.srcs/sources_1/bd/design_1/ip/design_1_ad9280_sample_0_0/src/afifo/afifo_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==afifo || ORIG_REF_NAME==afifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: F:/intel_project/AX7010/11_ad9280_dma_hdmi/ad9280_dma_hdmi.srcs/sources_1/bd/design_1/ip/design_1_ad9280_sample_0_0/design_1_ad9280_sample_0_0.xci
# IP: The module: 'design_1_ad9280_sample_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: f:/intel_project/AX7010/11_ad9280_dma_hdmi/ad9280_dma_hdmi.srcs/sources_1/bd/design_1/ip/design_1_ad9280_sample_0_0/src/afifo/afifo.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==afifo || ORIG_REF_NAME==afifo} -quiet] -quiet

# XDC: f:/intel_project/AX7010/11_ad9280_dma_hdmi/ad9280_dma_hdmi.srcs/sources_1/bd/design_1/ip/design_1_ad9280_sample_0_0/src/afifo/afifo.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==afifo || ORIG_REF_NAME==afifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: f:/intel_project/AX7010/11_ad9280_dma_hdmi/ad9280_dma_hdmi.srcs/sources_1/bd/design_1/ip/design_1_ad9280_sample_0_0/src/afifo/afifo_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==afifo || ORIG_REF_NAME==afifo} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
